import { Button } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'

export default function Home() {
    const count = useSelector(state => state.counter.value)
    return (
        <>
            <Head>
                <title>Test IMP</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className=''>
                <h1 className='text-3xl font-bold underline text-orange-400'>{count}</h1>
                <Button colorScheme='blue'>Button</Button>
            </main>
        </>
    )
}
